### PR TITLE
Added health bar!

### PR DESCRIPTION
**Pull request by GVulpoi**
Added health bar and implemented the rounding of health to a multiple of 10!

### CODE REVIEW

**Review by Mex777 — CHANGES_REQUESTED** [review]
Use snake_case instead of camelCase

**Review by Mex777 — CHANGES_REQUESTED** [review]
showHealth is still in cameCase...

**Review by Mex777 — APPROVED** [review]
Looks good, well done!

**Comment by Steven23X** [comment]
👍🏻 very nice pull request !!

**Pull request merged**
